name: Test Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu Çek
        uses: actions/checkout@v4

      - name: Bağımlılıkları Kur ve mkdtboimg Derle
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential bc bison ccache curl device-tree-compiler flex git libelf-dev libssl-dev dwarves python3 tar unzip zip
          
          # mkdtboimg aracını indirip derle ve sisteme ekle
          git clone https://android.googlesource.com/platform/system/tools/mkdtimg.git
          cd mkdtimg
          gcc -o mkdtboimg mkdtboimg.c
          sudo mv mkdtboimg /usr/local/bin/
          cd ..

      - name: Kernel Derle (build.sh Kullanarak)
        run: |
          chmod +x ./build.sh
          ./build.sh fire_defconfig -A -a

      - name: Çıktıları (AnyKernel3 ZIP) Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Flashable-Kernel-ZIP
          path: |
            dist/*.zip
            dist/*
            out/fire/arch/arm64/boot/Image*
            
